dist: trusty
language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    sources:
    - llvm-toolchain-trusty-3.9
    - llvm-toolchain-trusty-4.0
    packages:
    - libllvm3.5
    - llvm-3.5
    - libllvm3.6
    - llvm-3.6
    - libllvm3.9
    - llvm-3.9
    - libllvm4.0
    - llvm-4.0

# on travis, clang-3.5 in /usr/local includes an llvm-config
#   that comes earlier in the path than the system llvm
env:
    - LLVM_CONFIG=/usr/bin/llvm-config-3.5
    - LLVM_CONFIG=/usr/bin/llvm-config-3.6
    - LLVM_CONFIG=/usr/bin/llvm-config-3.9
    - LLVM_CONFIG=/usr/bin/llvm-config-4.0

install: "pip install -e ."
script:
    - python setup.py test
